### ISSUE TITLE
Pagina principal

### ISSUE THREAD

**Issue by alu0100769609** [alu0100769609/tareas-iniciales-alu0100769609#1]
Establecer la rama gh-pages como página principal del repositorio

**Comment by AdCalzadilla** [comment]
Para cambiar la rama principal debe seguir las siguientes instrucciones:
1. En el repositorio vaya a la pestaña **setting**.
2. En el menú de la izquierda elija la opción **branches**
3. Seleccione la rama que quiera poner como principal.
